# Generated by Django 4.1 on 2022-10-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_amenities_alter_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('seatnumber', models.CharField(max_length=100)),
                ('passing_year', models.CharField(max_length=100)),
                ('education_board', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField()),
                ('obtain_marks', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('field_name', models.CharField(max_length=100)),
                ('collage_name', models.CharField(max_length=100)),
                ('collage_address', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=100)),
                ('adhar_card', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('native', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='student/')),
                ('adhar_photo', models.ImageField(upload_to='adhar/')),
            ],
        ),
    ]
