# Generated by Django 4.1 on 2022-10-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='dept',
        ),
        migrations.RemoveField(
            model_name='student',
            name='adhar_card',
        ),
        migrations.RemoveField(
            model_name='student',
            name='adhar_photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='collage_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='collage_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='education_board',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='native',
        ),
        migrations.RemoveField(
            model_name='student',
            name='obtain_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='student',
            name='seatnumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_marks',
        ),
    ]
