# Generated by Django 4.1 on 2022-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_rename_city_student_dept_remove_student_adhar_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('field_name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
