# Generated by Django 4.1 on 2022-10-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0003_bad_room_room_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('day', models.CharField(max_length=100)),
                ('breakfast', models.CharField(max_length=100)),
                ('lunch', models.CharField(max_length=100)),
                ('dinner', models.CharField(max_length=100)),
            ],
        ),
    ]
