# Generated by Django 4.1 on 2022-10-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0005_meal_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
            ],
        ),
    ]
