# Generated by Django 4.1 on 2022-10-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0006_room_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room',
        ),
    ]
