# Generated by Django 4.1 on 2022-10-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0007_delete_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='room_students',
            new_name='room',
        ),
    ]
