# Generated by Django 4.1 on 2022-10-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0010_delete_bad_delete_room_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(unique=True)),
                ('first', models.IntegerField(unique=True)),
                ('second', models.IntegerField(unique=True)),
                ('third', models.IntegerField(unique=True)),
                ('fourth', models.IntegerField(unique=True)),
            ],
        ),
    ]
