# Generated by Django 4.1 on 2022-10-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0016_meet_delete_green_alter_event_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meet',
        ),
    ]
