# Generated by Django 4.1 on 2022-10-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0017_delete_meet'),
    ]

    operations = [
        migrations.CreateModel(
            name='meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
    ]
