# Generated by Django 4.1 on 2022-10-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_student_delete_registration'),
        ('second', '0019_vinit_delete_meet_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.student')),
            ],
        ),
        migrations.DeleteModel(
            name='vinit',
        ),
    ]
